In [2]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv(r"C:\Users\gopal\OneDrive\Desktop\Amazon E_Commerce Sales Analysis\cleaned_Amzon_sales.csv")
df.head(10)

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,...,ship-city,ship-state,B2B,Year,Month,Day,Quarter,Week,Order Category,Weekend
0,405-8078784-5731545,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,...,MUMBAI,MAHARASHTRA,False,2022,April,Saturday,2,17,Medium,True
1,171-9198151-1101146,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,...,BENGALURU,KARNATAKA,False,2022,April,Saturday,2,17,Low,True
2,404-0687676-7273146,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,...,NAVI MUMBAI,MAHARASHTRA,True,2022,April,Saturday,2,17,Low,True
3,403-9615377-8133951,2022-04-30,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,...,PUDUCHERRY,PUDUCHERRY,False,2022,April,Saturday,2,17,Medium,True
4,407-1069790-7240320,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,...,CHENNAI,TAMIL NADU,False,2022,April,Saturday,2,17,Medium,True
5,404-1490984-4578765,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,SET264,SET264-KR-NP-XL,Set,XL,...,GHAZIABAD,UTTAR PRADESH,False,2022,April,Saturday,2,17,Medium,True
6,408-5748499-6859555,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,J0095,J0095-SET-L,Set,L,...,CHANDIGARH,CHANDIGARH,False,2022,April,Saturday,2,17,Medium,True
7,406-7807733-3785945,2022-04-30,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3405,JNE3405-KR-S,kurta,S,...,HYDERABAD,TELANGANA,False,2022,April,Saturday,2,17,Low,True
8,407-5443024-5233168,2022-04-30,Cancelled,Amazon,Amazon.in,Expedited,SET200,SET200-KR-NP-A-XXXL,Set,3XL,...,HYDERABAD,TELANGANA,False,2022,April,Saturday,2,17,Medium,True
9,402-4393761-0311520,2022-04-30,Shipped,Amazon,Amazon.in,Expedited,JNE3461,JNE3461-KR-XXL,kurta,XXL,...,Chennai,TAMIL NADU,False,2022,April,Saturday,2,17,Low,True

1. Total Revenue

In [7]:
total_revenue = df["Amount"].sum()
print(f"Total Revenue : Rs.{total_revenue:,.2f}")

Total Revenue : Rs.83,304,203.30

2. Total Orders

In [9]:
Total_orders = len(df)
print("Total order :", Total_orders)

Total order : 128969

3. Total Quantity sold :

In [10]:
total_quantity = df["Qty"].sum()
print("Total Quantity Sold :-", total_quantity)

Total Quantity Sold :- 116646

4. Average Order Value :

In [12]:
avg_order_value = df["Amount"].mean()
print(f"Average_Order_Value :- Rs.{avg_order_value:.0f}")

Average_Order_Value :- Rs.646

5. Maximum Order Value :

In [13]:
max_order = df["Amount"].max()
print(f"Maximum order value :- Rs.{max_order:.0f}")

Maximum order value :- Rs.5584

6. Cancellation Rate

In [17]:
lenght = len(df)
cancel_order = df["Status"].str.contains(
    "Cancelled",
    case=False,
    na=False
).sum()
cancel_rate = (cancel_order/lenght)*100
print(f"Cancellatio Rate : {cancel_rate:.0f}%")

Cancellatio Rate : 14%

7. Delivery rate

In [21]:
delivered = df["Courier Status"].str.contains(
    "Shipped",
    case=False,
    na=False
    
).sum()
delivery_rate = (delivered/len(df))*100
print(f"Delivery Rate :- {delivery_rate:.2f}%")

Delivery Rate :- 90.07%

8. Top 10 Categories by Revenue

In [24]:
top_catrgories = df.groupby("Category")["Amount"].sum().nlargest(10).reset_index(name="Total Revenue")
top_catrgories

        Category  Total Revenue
0            Set    41162827.03
1          kurta    23209603.70
2  Western Dress    11697652.69
3            Top     5624277.30
4   Ethnic Dress      831147.66
5         Blouse      485633.18
6         Bottom      162767.98
7          Saree      129378.76
8        Dupatta         915.00

9. Top 10 States by revenue

In [28]:
top_states = df.groupby("ship-state")["Amount"].sum().nlargest(10).reset_index(name="Total_Revenue")
top_states

       ship-state  Total_Revenue
0     MAHARASHTRA    14052730.14
1       KARNATAKA    11044369.37
2       TELANGANA     7335880.65
3   UTTAR PRADESH     7234164.08
4      TAMIL NADU     6923420.11
5           DELHI     4470560.97
6          KERALA     4092192.58
7     WEST BENGAL     3758955.44
8  ANDHRA PRADESH     3446706.72
9         HARYANA     3019427.99

10. Top 10 states and cities total revenue

In [32]:
top_city_states_revenue = df.groupby(["ship-state", "ship-city"])["Amount"].sum().nlargest(10).reset_index(name="total_revenue")
top_city_states_revenue

      ship-state  ship-city  total_revenue
0      KARNATAKA  BENGALURU     7170919.99
1      TELANGANA  HYDERABAD     5223666.82
2    MAHARASHTRA     MUMBAI     3861156.80
3          DELHI  NEW DELHI     3816861.83
4     TAMIL NADU    CHENNAI     3274800.74
5    MAHARASHTRA       PUNE     2458579.18
6    WEST BENGAL    KOLKATA     1497258.87
7        HARYANA   GURUGRAM     1273043.74
8    MAHARASHTRA      THANE     1061225.29
9  UTTAR PRADESH    LUCKNOW      996846.34

11. Revenue by Size

In [34]:
size_wise_revenue = df.groupby("Size")["Amount"].sum().reset_index(name="total_revenue")
size_wise_revenue

    Size  total_revenue
0    3XL     9618834.68
1    4XL      345946.64
2    5XL      439676.63
3    6XL      596214.33
4   Free      218502.77
5      L    14039536.19
6      M    14763481.37
7      S    11317095.18
8     XL    13159776.86
9     XS     7545700.20
10   XXL    11259438.45

12. Revenue by Fulfilment

In [35]:
fulfilment_sales = df.groupby("Fulfilment")["Amount"].sum().reset_index(name="total_revenue")
fulfilment_sales

  Fulfilment  total_revenue
0     Amazon     57983396.0
1   Merchant     25320807.3

13. Revenue by Courier Status

In [36]:
courier_sales = df.groupby("Courier Status")["Amount"].sum().reset_index(name="Total Qty")
courier_sales

  Courier Status   Total Qty
0      Cancelled   3588860.0
1        Shipped  71056029.0
2        Unknown   4240452.3
3      Unshipped   4418862.0

14. find states whose revenue is greater then avg revenue

In [38]:
state_revenue = df.groupby("ship-state")["Amount"].sum().reset_index(name="Total Rvn")
avg_revenue = state_revenue["Total Rvn"].mean()
above_avg_rvn = state_revenue[state_revenue["Total Rvn"] > avg_revenue].sort_values(by="Total Rvn", ascending=False)
#print("Average Revenue :", round(avg_revenue, 2))
print(above_avg_rvn)

        ship-state    Total Rvn
28     MAHARASHTRA  14052730.14
23       KARNATAKA  11044369.37
57       TELANGANA   7335880.65
59   UTTAR PRADESH   7234164.08
56      TAMIL NADU   6923420.11
14           DELHI   4470560.97
24          KERALA   4092192.58
62     WEST BENGAL   3758955.44
1   ANDHRA PRADESH   3446706.72
19         HARYANA   3019427.99
18         Gujarat   2931931.82
49       RAJASTHAN   1826912.40
27  MADHYA PRADESH   1690392.98
8            BIHAR   1485743.32
39          ODISHA   1456905.63
44          PUNJAB   1246009.84

15. Total Shipped revenue

In [40]:
df[df["Courier Status"]=="Shipped"]["Amount"].sum()

np.float64(71056029.0)

In [46]:
df.groupby("ship-service-level").size()

ship-service-level
Expedited    88609
Standard     40360
dtype: int64

17. Monthly total Revenue

In [48]:
df.groupby("Month")["Amount"].sum().reset_index(name='Total Revenue').sort_values(by="Total Revenue")

   Month  Total Revenue
2  March      107128.85
1   June    24805861.38
3    May    27739319.75
0  April    30651893.32

18. Monthly and day wise total revenue

In [49]:
df.groupby(["Month", "Day"])["Amount"].sum().reset_index(name="Total_Revenue")

    Month        Day  Total_Revenue
0   April     Friday     5068151.61
1   April     Monday     3939811.78
2   April   Saturday     5268165.29
3   April     Sunday     4334780.26
4   April   Thursday     4075110.58
5   April    Tuesday     3935418.25
6   April  Wednesday     4030455.55
7    June     Friday     3094370.52
8    June     Monday     3484130.17
9    June   Saturday     3318684.40
10   June     Sunday     3643205.47
11   June   Thursday     3487838.89
12   June    Tuesday     3645232.24
13   June  Wednesday     4132399.69
14  March   Thursday      107128.85
15    May     Friday     3321682.47
16    May     Monday     4571494.19
17    May   Saturday     3395622.88
18    May     Sunday     4730870.57
19    May   Thursday     3309850.95
20    May    Tuesday     4619168.58
21    May  Wednesday     3790630.11

19. Weekend total sales

In [52]:
df[df["Weekend"]==True]["Amount"].sum()

np.float64(24691328.869999997)

In [51]:
df.groupby("Weekend")["Amount"].sum()

Weekend
False    58612874.43
True     24691328.87
Name: Amount, dtype: float64

20. state wise KPIs

In [54]:
state_kpi = df.groupby("ship-state").agg({
    "Amount" : ["sum", "mean"],
    "Qty" : "sum"
})
state_kpi

                        Amount               Qty
                           sum        mean   sum
ship-state
ANDAMAN & NICOBAR    167193.62  650.558833   226
ANDHRA PRADESH      3446706.72  634.752619  4819
APO                     605.00  605.000000     0
AR                      493.00  493.000000     1
ARUNACHAL PRADESH     99470.00  705.460993   130
...                        ...         ...   ...
goa                    2467.00  493.400000     5
orissa                  597.00  597.000000     1
punjab                 9227.00  659.071429    13
rajasthan              3946.00  657.666667     6
rajsthan                521.00  521.000000     1

[70 rows x 3 columns]

In [55]:
df.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'Amount', 'ship-city', 'ship-state', 'B2B',
       'Year', 'Month', 'Day', 'Quarter', 'Week', 'Order Category', 'Weekend'],
      dtype='object')