In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv(r"C:\Users\gopal\OneDrive\Desktop\Amazon E_Commerce Sales Analysis\Amazon_sales_dataset.csv")
df

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,Amount,ship-city,ship-state,B2B
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,647.62,MUMBAI,MAHARASHTRA,False
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,406.00,BENGALURU,KARNATAKA,False
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,True
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,False
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,574.00,CHENNAI,TAMIL NADU,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,Shipped,1,517.00,HYDERABAD,TELANGANA,False
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,B09VC6KHX8,Shipped,1,999.00,GURUGRAM,HARYANA,False
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,Shipped,1,690.00,HYDERABAD,TELANGANA,False
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,B0894Y2NJQ,Shipped,1,1199.00,Halol,Gujarat,False
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,B0894X27FC,Shipped,1,696.00,Raipur,CHHATTISGARH,False

In [3]:
df.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'Amount', 'ship-city', 'ship-state', 'B2B'],
      dtype='object')

In [4]:
df.to_excel("Amazon_sales_dataset.xlsx", index=False)
df.to_csv("Amazon_sales_dataset.csv", index=False)

In [5]:
df.head()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,Amount,ship-city,ship-state,B2B
0,405-8078784-5731545,04-30-22,Cancelled,Merchant,Amazon.in,Standard,SET389,SET389-KR-NP-S,Set,S,B09KXVBD7Z,NaN,0,647.62,MUMBAI,MAHARASHTRA,False
1,171-9198151-1101146,04-30-22,Shipped - Delivered to Buyer,Merchant,Amazon.in,Standard,JNE3781,JNE3781-KR-XXXL,kurta,3XL,B09K3WFS32,Shipped,1,406.00,BENGALURU,KARNATAKA,False
2,404-0687676-7273146,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3371,JNE3371-KR-XL,kurta,XL,B07WV4JV4D,Shipped,1,329.00,NAVI MUMBAI,MAHARASHTRA,True
3,403-9615377-8133951,04-30-22,Cancelled,Merchant,Amazon.in,Standard,J0341,J0341-DR-L,Western Dress,L,B099NRCT7B,NaN,0,753.33,PUDUCHERRY,PUDUCHERRY,False
4,407-1069790-7240320,04-30-22,Shipped,Amazon,Amazon.in,Expedited,JNE3671,JNE3671-TU-XXXL,Top,3XL,B098714BZP,Shipped,1,574.00,CHENNAI,TAMIL NADU,False

In [6]:
df.tail()

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,Qty,Amount,ship-city,ship-state,B2B
128970,406-6001380-7673107,05-31-22,Shipped,Amazon,Amazon.in,Expedited,JNE3697,JNE3697-KR-XL,kurta,XL,B098112V2V,Shipped,1,517.0,HYDERABAD,TELANGANA,False
128971,402-9551604-7544318,05-31-22,Shipped,Amazon,Amazon.in,Expedited,SET401,SET401-KR-NP-M,Set,M,B09VC6KHX8,Shipped,1,999.0,GURUGRAM,HARYANA,False
128972,407-9547469-3152358,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0157,J0157-DR-XXL,Western Dress,XXL,B0982YZ51B,Shipped,1,690.0,HYDERABAD,TELANGANA,False
128973,402-6184140-0545956,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0012,J0012-SKD-XS,Set,XS,B0894Y2NJQ,Shipped,1,1199.0,Halol,Gujarat,False
128974,408-7436540-8728312,05-31-22,Shipped,Amazon,Amazon.in,Expedited,J0003,J0003-SET-S,Set,S,B0894X27FC,Shipped,1,696.0,Raipur,CHHATTISGARH,False

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 128975 entries, 0 to 128974
Data columns (total 17 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   Order ID            128975 non-null  object
 1   Date                128975 non-null  object
 2   Status              128975 non-null  object
 3   Fulfilment          128975 non-null  object
 4   Sales Channel       128975 non-null  object
 5   ship-service-level  128975 non-null  object
 6   Style               128975 non-null  object
 7   SKU                 128975 non-null  object
 8   Category            128975 non-null  object
 9   Size                128975 non-null  object
 10  ASIN                128975 non-null  object
 11  Courier Status      122103 non-null  object
 12  Qty                 128975 non-null  int64
 13  Amount              121180 non-null  float64
 14  ship-city           128942 non-null  object
 15  ship-state          128942 non-null  object
 16  B2B                 128975 non-null  bool
dtypes: bool(1), float64(1), int64(1), object(14)
memory usage: 15.9+ MB

In [8]:
df.shape

(128975, 17)

In [9]:
df.describe()

                 Qty         Amount
count  128975.000000  121180.000000
mean        0.904431     648.561465
std         0.313354     281.211687
min         0.000000       0.000000
25%         1.000000     449.000000
50%         1.000000     605.000000
75%         1.000000     788.000000
max        15.000000    5584.000000

In [10]:
df.describe(include="object")

,Order ID,Date,Status,Fulfilment,Sales Channel,ship-service-level,Style,SKU,Category,Size,ASIN,Courier Status,ship-city,ship-state
count,128975,128975,128975,128975,128975,128975,128975,128975,128975,128975,128975,122103,128942,128942
unique,120378,91,13,2,2,2,1377,7195,9,11,7190,3,8955,69
top,171-5057375-2831560,05-03-22,Shipped,Amazon,Amazon.in,Expedited,JNE3797,JNE3797-KR-L,Set,M,B09SDXFFQ1,Shipped,BENGALURU,MAHARASHTRA
freq,12,2085,77804,89698,128851,88615,4224,773,50284,22711,773,109487,11217,22260

In [11]:
df.dtypes

Order ID               object
Date                   object
Status                 object
Fulfilment             object
Sales Channel          object
ship-service-level     object
Style                  object
SKU                    object
Category               object
Size                   object
ASIN                   object
Courier Status         object
Qty                     int64
Amount                float64
ship-city              object
ship-state             object
B2B                      bool
dtype: object

In [12]:
df.isnull().sum()

Order ID                 0
Date                     0
Status                   0
Fulfilment               0
Sales Channel            0
ship-service-level       0
Style                    0
SKU                      0
Category                 0
Size                     0
ASIN                     0
Courier Status        6872
Qty                      0
Amount                7795
ship-city               33
ship-state              33
B2B                      0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(6)

In [14]:
df = df.drop_duplicates()

In [15]:
df["Date"] = pd.to_datetime(df["Date"])

In [16]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month_name()
df["Day"] = df["Date"].dt.day_name()
df["Quarter"] = df["Date"].dt.quarter

In [17]:
df["Courier Status"] = df["Courier Status"].fillna("Unknown")

In [18]:
df["Amount"] = df["Amount"].fillna(df["Amount"].median())

In [19]:
df["ship-city"] = df["ship-city"].fillna("Unknown")
df["ship-state"] = df["ship-state"].fillna("Unknown")

In [20]:
df.isnull().sum()

Order ID              0
Date                  0
Status                0
Fulfilment            0
Sales Channel         0
ship-service-level    0
Style                 0
SKU                   0
Category              0
Size                  0
ASIN                  0
Courier Status        0
Qty                   0
Amount                0
ship-city             0
ship-state            0
B2B                   0
Year                  0
Month                 0
Day                   0
Quarter               0
dtype: int64

In [21]:
df.to_csv("Cleaned_Amazon_Sales_dataset.csv")

In [22]:
df.columns

Index(['Order ID', 'Date', 'Status', 'Fulfilment', 'Sales Channel ',
       'ship-service-level', 'Style', 'SKU', 'Category', 'Size', 'ASIN',
       'Courier Status', 'Qty', 'Amount', 'ship-city', 'ship-state', 'B2B',
       'Year', 'Month', 'Day', 'Quarter'],
      dtype='object')

In [23]:
category_revenue = df.groupby("Category")["Amount"].sum()
category_revenue.sort_values(ascending=False)

Category
Set              41162827.03
kurta            23209603.70
Western Dress    11697652.69
Top               5624277.30
Ethnic Dress       831147.66
Blouse             485633.18
Bottom             162767.98
Saree              129378.76
Dupatta               915.00
Name: Amount, dtype: float64

In [24]:
df.value_counts("Size").head(1)

Size
M    22709
Name: count, dtype: int64

In [25]:
df["Fulfilment"].value_counts()

Fulfilment
Amazon      89692
Merchant    39277
Name: count, dtype: int64

In [26]:
state_ravenue = df.groupby("ship-state")["Amount"].sum().sort_values(ascending=False).head(1)
state_ravenue

ship-state
MAHARASHTRA    14052730.14
Name: Amount, dtype: float64

In [27]:
month_revenue = df.groupby("Month")["Amount"].sum().reset_index(name="Total").sort_values(by="Total", ascending=False)
month_revenue

   Month        Total
0  April  30651893.32
3    May  27739319.75
1   June  24805861.38
2  March    107128.85

In [28]:
total_order = len(df)

cancel_orders = df["Status"].str.contains(
    "Cancelled",
    case=False,
    na=False
).sum()

cancellation_rate = (cancel_orders/total_order)*100

#total_order
#cancel_orders
print(f"cancellation_Rate:{cancellation_rate:.1f}%")

cancellation_Rate:14.2%

In [29]:
sku_most_sale = df.groupby("SKU")["Amount"].sum().sort_values(ascending=False).head(5)
sku_most_sale

SKU
JNE3797-KR-L    555436.77
J0230-SKD-M     547711.20
J0230-SKD-S     494457.14
JNE3797-KR-M    476070.16
JNE3797-KR-S    427872.57
Name: Amount, dtype: float64

In [30]:
df["Amount"].mean()

np.float64(645.9242399336275)

In [31]:
total_order_by_category = df.groupby("Category").size()
total_order_by_category

Category
Blouse             926
Bottom             440
Dupatta              3
Ethnic Dress      1159
Saree              164
Set              50281
Top              10622
Western Dress    15500
kurta            49874
dtype: int64

In [32]:
cancellation_order = (
    df[df["Status"].str.contains("Cancelled", case=False, na=False)].groupby("Category").size()
)
cancellation_order

Category
Blouse            116
Bottom             60
Ethnic Dress      145
Saree              21
Set              7336
Top              1276
Western Dress    2122
kurta            7253
dtype: int64

In [33]:
cancellation_rate_by_category = (cancellation_order/total_order_by_category)*100
cancellation_rate_by_category.sort_values(ascending=False).head(1)

Category
Set    14.590004
dtype: float64

In [34]:
df["Week"] = df["Date"].dt.isocalendar().week

In [37]:
def order_category(amount):
    if amount < 500:
        return "Low"
    elif amount < 1500:
        return "Medium"
    elif amount < 3000:
        return "High"
    else:
        return "Premium"
    
df["Order Category"] = df["Amount"].apply(order_category)

In [39]:
df["Weekend"] = df["Day"].isin(["Saturday", "Sunday"])

In [40]:
df.to_excel("Cleaned_dataset.xlsx", index=False)

In [41]:
df.to_csv("cleaned_Amzon_sales.csv", index=False)